# Generated by Django 5.2.7 on 2025-11-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_update_employees_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='work_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Рабочий телефон'),
        ),
    ]
