# Generated by Django 5.2.7 on 2025-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employees_work_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='full_name_accusative',
            field=models.CharField(blank=True, max_length=300, verbose_name='ФИО в винительном падеже'),
        ),
        migrations.AddField(
            model_name='employees',
            name='ip_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='IP-телефон'),
        ),
    ]
