# Generated by Django 5.2.7 on 2025-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='departments',
            name='is_logical',
            field=models.BooleanField(default=False, verbose_name='Логическое подразделение'),
        ),
        migrations.AddField(
            model_name='departments',
            name='sorting',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сокращенное наименование (для сортировки)'),
        ),
    ]
