# Generated by Django 5.2.7 on 2025-10-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_departments_options_departments_is_logical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postname',
            name='sorting',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код сортировки'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='sorting',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код сортировки'),
        ),
    ]
