# Generated by Django 5.2.7 on 2025-10-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_postname_sorting_alter_departments_sorting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postname',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
