# Generated by Django 5.2.7 on 2025-11-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_alter_postname_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('asset_type', models.CharField(choices=[('system', 'Информационная система'), ('service', 'Сервис'), ('application', 'Приложение'), ('database', 'База данных'), ('infrastructure', 'Инфраструктурный объект'), ('other', 'Другое')], default='system', max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='URL/Ссылка')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Версия')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('development', 'В разработке'), ('maintenance', 'На обслуживании'), ('deprecated', 'Устаревшая'), ('inactive', 'Неактивна')], default='active', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_assets', to='reference.departments', verbose_name='Подразделение-владелец')),
            ],
            options={
                'verbose_name': 'Информационный актив',
                'verbose_name_plural': 'Информационные активы',
                'ordering': ['name'],
            },
        ),
    ]
