# Generated by Django 5.2.7 on 2025-11-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_itasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itasset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='code',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='owner_department',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='url',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='version',
        ),
    ]
