# Generated by Django 5.2.7 on 2025-11-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_remove_itasset_asset_type_remove_itasset_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITAsset',
        ),
    ]
