# Generated by Django 5.2.7 on 2025-11-03 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_migrate_certificate_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='bldg',
            field=models.CharField(blank=True, max_length=50, verbose_name='Здание/Строение'),
        ),
        migrations.AddField(
            model_name='departments',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='departments',
            name='dep_short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Короткое наименование'),
        ),
        migrations.AddField(
            model_name='departments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Официальный адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='departments',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Начальный IP адрес сети'),
        ),
        migrations.AddField(
            model_name='departments',
            name='mask',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)], verbose_name='Префикс маски подсети (0-32)'),
        ),
        migrations.AddField(
            model_name='departments',
            name='net_id',
            field=models.CharField(blank=True, max_length=4, verbose_name='Идентификатор сетевого узла'),
        ),
        migrations.AddField(
            model_name='departments',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='departments',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс'),
        ),
    ]
