# Generated by Django 5.2.3 on 2025-06-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название набора')),
                ('description', models.TextField(verbose_name='Пояснение к набору')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('option_1', models.CharField(max_length=500, verbose_name='Вариант ответа 1')),
                ('option_2', models.CharField(max_length=500, verbose_name='Вариант ответа 2')),
                ('option_3', models.CharField(max_length=500, verbose_name='Вариант ответа 3')),
                ('option_4', models.CharField(max_length=500, verbose_name='Вариант ответа 4')),
                ('correct_option', models.IntegerField(choices=[(1, 'Вариант 1'), (2, 'Вариант 2'), (3, 'Вариант 3'), (4, 'Вариант 4')], verbose_name='Правильный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.questionset', verbose_name='Набор вопросов')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание теста')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль для доступа')),
                ('time_limit', models.IntegerField(verbose_name='Время в минутах')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность теста')),
                ('questions_per_set', models.IntegerField(default=5, verbose_name='Количество случайных вопросов из каждого набора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_sets', models.ManyToManyField(to='tests.questionset', verbose_name='Наборы вопросов')),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('selected_questions', models.JSONField(verbose_name='Список ID выбранных вопросов')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(verbose_name='Общее количество вопросов')),
                ('answered_questions', models.IntegerField(verbose_name='Количество отвеченных вопросов')),
                ('correct_answers', models.IntegerField(verbose_name='Количество правильных ответов')),
                ('skipped_questions', models.IntegerField(verbose_name='Количество пропущенных вопросов')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент правильных ответов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tests.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(blank=True, null=True, verbose_name='Выбранный вариант')),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='tests.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
