# Generated by Django 5.2.3 on 2025-06-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_testresult_skipped_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='skipped_questions',
            field=models.IntegerField(default=1, verbose_name='Количество пропущенных вопросов'),
            preserve_default=False,
        ),
    ]
