# Generated by Django 5.2.7 on 2025-10-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testresult_skipped_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionset',
            options={'verbose_name': 'Набор вопросов', 'verbose_name_plural': 'Наборы вопросов'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'verbose_name': 'Сессия тестирования', 'verbose_name_plural': 'Сессии тестирования'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
    ]
