# Generated by Django 5.2.7 on 2025-10-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_alter_postname_options'),
        ('tests', '0004_alter_question_options_alter_questionset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.departments', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='postname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.postname', verbose_name='Должность'),
        ),
    ]
