# Generated by Django 5.2.7 on 2025-01-27 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_testsession_department_testsession_postname'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP-адрес'),
        ),
    ]

