# Generated by Django 5.2.7 on 2025-01-27 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_testsession_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]

