# Generated by Django 5.2.7 on 2025-11-02 17:12

import apps.access_management.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_alter_employees_gender'),
        ('reference', '0008_itasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип сертификата',
                'verbose_name_plural': 'Типы сертификатов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_serial', models.CharField(max_length=200, verbose_name='Серийный номер сертификата')),
                ('certificate_alias', models.CharField(max_length=200, verbose_name='Отпечаток сертификата (alias)')),
                ('expiry_date', models.DateField(verbose_name='Дата окончания срока действия')),
                ('carrier_serial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Серийный номер носителя (токен)')),
                ('certificate_file', models.FileField(help_text='Форматы: .cer, .pfx. Максимальный размер: 1 МБ', upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cer', 'pfx']), apps.access_management.models.validate_file_size], verbose_name='Файл сертификата')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('revoked', 'Аннулирована'), ('needs_update', 'Требует актуализации')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_management.certificatetype', verbose_name='Тип сертификата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Цифровая подпись',
                'verbose_name_plural': 'Цифровые подписи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('suspended', 'Приостановлен'), ('blocked', 'Заблокирован'), ('deleted', 'Удален'), ('needs_update', 'Требует актуализации')], default='active', max_length=20, verbose_name='Статус')),
                ('access_granted_date', models.DateField(verbose_name='Дата получения доступа')),
                ('access_blocked_date', models.DateField(blank=True, null=True, verbose_name='Дата блокировки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employees', verbose_name='Сотрудник')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.itasset', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Доступ к системе',
                'verbose_name_plural': 'Доступы к системам',
                'ordering': ['-created_at'],
            },
        ),
    ]
