# Generated by Django 5.2.7 on 2025-11-02 17:13

import apps.access_management.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalsignature',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Форматы: .cer, .pfx. Максимальный размер: 1 МБ', null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cer', 'pfx']), apps.access_management.models.validate_file_size], verbose_name='Файл сертификата'),
        ),
    ]
