# Generated by Django 5.2.7 on 2025-11-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0002_alter_digitalsignature_certificate_file'),
        ('reference', '0010_migrate_certificate_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalsignature',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.certificatetype', verbose_name='Тип сертификата'),
        ),
        migrations.DeleteModel(
            name='CertificateType',
        ),
    ]
